config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView
from django.views import defaults as default_views
from rest_framework.documentation import include_docs_urls
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token

from polls.pollsapp import views, viewsets
from polls.pollsapp.viewsets import QuestionViewSet, ResultsViewSet

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path('pollsapp/', include('polls.pollsapp.urls', namespace='pollsapp')), #this makes sure the urls.py file at this dir is taken into account
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

# Django Admin, use {% url 'admin:index' %}
admin.site.site_header = _('Polls Admin')
urlpatterns += [
    path(settings.ADMIN_URL, admin.site.urls),
]

# API URLs
# Create a router and register our resources with it.
urlpatterns += [
    # V1
    # JWT Token
    path('api/v1/auth/jwt/token/', obtain_jwt_token),
    path('api/v1/auth/jwt/refresh/', refresh_jwt_token),
    path('api/v1/auth/jwt/verify/', verify_jwt_token),
    
    # Docs
    path('api/v1/docs/', include_docs_urls(title='Polls API', public=False)),
    # Endpoints
    path('api/v1/', include('config.router', namespace="api_v1")),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

polls/pollsapp/urls.py
from django.conf import settings
from django.urls import path, include
from polls.pollsapp import views

#register app name!
app_name = 'pollsapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/pollsapp/models.py
import datetime

from django.db import models
from django.utils import timezone

from polls.users.models import User

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(default=timezone.now)#('date published')
    owner = models.ForeignKey(User, related_name='questions', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def create(self, validated_data):
        return Question.objects.create(**validated_data)

    def update(self, instance, validated_data):
        instance.question_text = validated_data.get('question_text', instance.question_text)
        instance.save()
        return instance

    def save(self, *args, **kwargs):
        super(Question, self).save(*args, **kwargs)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    owner = models.ForeignKey(User, related_name='choices', null=True, blank=True, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.choice_text

polls/pollsapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from polls.pollsapp.models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'pollsapp/index.html' #make sure when testing for this that test reflects this link
    context_object_name = 'latest_question_list'
    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'pollsapp/detail.html'

    def get_queryset(self):
        #excludes any questions that aren't published yet.
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'pollsapp/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'pollsapp/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('pollsapp:results', args=(question.id,)))

polls/pollsapp/templates/pollsapp/detail.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Polls App</title>
        <link rel="stylesheet" type="text/css" href="{% static 'pollsapp/style.css' %}">
    </head>
    <body>
        <h1>test</h1>
        <h1>{{ question.question_text }}</h1>

        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <form action="{% url 'pollsapp:vote' question.id %}" method="post">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
            <input type="submit" value="Vote">
        </form>
    </body>
</html>

polls/pollsapp/templates/pollsapp/index.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Polls App</title>
        <link rel="stylesheet" type="text/css" href="{% static 'pollsapp/style.css' %}">
    </head>
    <body>
        {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li>
                    <a href="{% url 'pollsapp:detail' question.id %}/">
                        {{ question.question_text }}
                    </a>
                </li>
            {% endfor %}
        </ul>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
    </body>
</html>

polls/pollsapp/templates/pollsapp/results.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Polls App</title>
    </head>
    <body>
        <h1>{{ question.question_text }}</h1>

        <ul>
            {% for choice in question.choice_set.all %}
            <li>
                {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
            </li>
            {% endfor %}
        </ul>

        <a href="{% url 'pollsapp:detail' question.id %}">Vote again?</a>
    </body>
</html>